.pragma library
var W_LEFT = 20;
var W_RIGHT = 45;
var H_TOP = 20
var H_BOTTOM = 36

var MARGIN_TOP = 7;
var MARGIN_BOTTOM = 25;
var MARGIN_LEFT_TEXT = 10;
var MARGIN_RIGHT_BUBBLE = 10;
var MARGIN_RIGHT_TEXT = 10;
var MARGIN_LEFT_BUBBLE = 10;
var MARGIN_NOTE_RIGHT = 45;
var MARGIN_NOTE_BOTTOM = -6;

var MESSAGE_FONT_SIZE = 28;
var MESSAGE_FONT_COLOR = "#202020"

var NOTE_FONT_SIZE = 18;
var NOTE_FONT_COLOR = "black"


